package com.pollhq.mymavenproject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AnalyticsWindow extends HorizontalLayout {
	protected HorizontalLayout menuTitle;
	protected Label menuTitleLabel;
	protected CssLayout menuItems;
	protected Button pollButton;
	protected Button createButton;
	protected Button dataButton;
	protected Button friendsButton;
	protected Button giftButton;
	protected Button accountButton;
	protected Button logoutButton;
	protected Label titleLabel;
	protected ComboBox choiceBox;
	protected Button chartButton;
	protected Panel chartPanel;
	protected VerticalLayout vertLayout;

	public AnalyticsWindow() {
		Design.read(this);
	}
}
