package com.pollhq.mymavenproject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PollDesign extends VerticalLayout {
	protected Label questionLabel;
	protected Label likeLabel;
	protected Button linkButton;
	protected Button likeButton;
	protected Button shareButton;

	public PollDesign() {
		Design.read(this);
	}
}
